# Generated by Django 6.1 on 2026-08-28 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_alter_studentprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='campus',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='election',
            name='election_type',
            field=models.CharField(choices=[('INSTITUTIONAL', 'Institutional SRC'), ('CAMPUS', 'Campus SRC'), ('RUNOFF', 'Runoff')], default='INSTITUTIONAL', max_length=20),
        ),
    ]
