# Generated by Django 6.1 on 2026-08-29 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_election_campus_election_election_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='candidate_type',
            field=models.CharField(choices=[('ORGANIZATION', 'Organization'), ('INDEPENDENT', 'Independent Candidate')], default='ORGANIZATION', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='candidate_images/'),
        ),
    ]
