# Generated by Django 6.1 on 2026-09-13 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_candidate_candidate_type_candidate_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='src_category',
            field=models.CharField(choices=[('INSTITUTIONAL', 'Institutional SRC'), ('CAMPUS', 'Campus SRC')], default='INSTITUTIONAL', max_length=20),
        ),
    ]
