# Generated by Django 6.1 on 2026-09-14 00:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0006_candidate_src_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vote',
            name='one_vote_per_voter_per_election',
        ),
        migrations.AddField(
            model_name='vote',
            name='src_category',
            field=models.CharField(blank=True, choices=[('INSTITUTIONAL', 'Institutional SRC'), ('CAMPUS', 'Campus SRC')], max_length=20, null=True),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('voter', 'election', 'src_category'), name='one_vote_per_category_per_election'),
        ),
    ]
